In [1]:
# numpy kütüphanesini "np" takma adıyla içe aktarıyoruz (topluluk standardı)
import numpy as np
import csv

print("NumPy versiyonu:", np.__version__)

NumPy versiyonu: 2.4.4


In [2]:
# CSV dosyasını satır satır okuyoruz
with open("Student_Performance.csv", "r") as f:
    okuyucu = csv.reader(f)
    basliklar = next(okuyucu)          # ilk satır sütun isimleri
    satirlar = list(okuyucu)           # geri kalan tüm satırlar

print("Sütunlar:", basliklar)
print("Toplam öğrenci sayısı:", len(satirlar))

Sütunlar: ['student_id', 'age', 'gender', 'school_type', 'parent_education', 'study_hours', 'attendance_percentage', 'internet_access', 'travel_time', 'extra_activities', 'study_method', 'math_score', 'science_score', 'english_score', 'overall_score', 'final_grade']
Toplam öğrenci sayısı: 25000


In [3]:
# Sayısal sütunları seçip NumPy array'lerine dönüştürüyoruz
# Sütun indeksleri: 1=age, 5=study_hours, 6=attendance_percentage,
#                   11=math_score, 12=science_score, 13=english_score, 14=overall_score

yas          = np.array([int(s[1])     for s in satirlar])   # yaş -> tam sayı (int)
calisma_saat = np.array([float(s[5])   for s in satirlar])   # günlük çalışma saati -> ondalıklı (float)
devam        = np.array([float(s[6])   for s in satirlar])   # devam yüzdesi
matematik    = np.array([float(s[11])  for s in satirlar])   # matematik notu (ondalıklı!)
fen          = np.array([float(s[12])  for s in satirlar])   # fen notu
ingilizce    = np.array([float(s[13])  for s in satirlar])   # İngilizce notu
final_yuzde  = np.array([float(s[14])  for s in satirlar])   # genel başarı skoru (overall_score)

# Kategorik sütunlar (metin olarak kalacak)
cinsiyet    = np.array([s[2]  for s in satirlar])   # male / female
not_harfi   = np.array([s[15] for s in satirlar])   # final_grade: a,b,c,d,e,f (f = kaldı)

print("Matematik notları (ilk 10):", matematik[:10])

Matematik notları (ilk 10): [42.7 57.6 84.8 44.4  8.9 51.5 41.9 56.7 54.1 71.9]


In [4]:
print("shape :", matematik.shape)   # kaç elemanlı olduğunu gösterir
print("ndim  :", matematik.ndim)    # boyut sayısı (1D)
print("size  :", matematik.size)    # toplam eleman sayısı
print("dtype :", matematik.dtype)   # veri tipi (float64 -> bu veri setinde notlar ondalıklı)
print()
print("Çalışma saati dtype:", calisma_saat.dtype)  # float64 -> ondalıklı değerler

shape : (25000,)
ndim  : 1
size  : 25000
dtype : float64

Çalışma saati dtype: float64


In [5]:
# Üç dersin notlarını tek bir 2D matris haline getirelim (derste gördüğümüz 2D array mantığı)
# np.column_stack: 1D array'leri sütun sütun yan yana dizerek matris oluşturur
notlar = np.column_stack([matematik, fen, ingilizce])

print("Notlar matrisi shape:", notlar.shape)   # (25000, 3) -> 25000 satır (öğrenci), 3 sütun (ders)
print("İlk 5 öğrencinin notları:")
print(notlar[:5])

Notlar matrisi shape: (25000, 3)
İlk 5 öğrencinin notları:
[[42.7 55.4 57. ]
 [57.6 68.8 64.8]
 [84.8 95.  79.2]
 [44.4 27.5 54.7]
 [ 8.9 32.7 30. ]]


In [6]:
print("İlk öğrencinin matematik notu :", matematik[0])
print("Son öğrencinin matematik notu :", matematik[-1])    # negatif indeks sondan sayar
print("5-10 arası öğrencilerin notları:", matematik[5:10]) # dilimleme (slicing)
print()
# 2D matriste indeksleme: [satır, sütun]
print("3. öğrencinin fen notu        :", notlar[2, 1])     # 2. indeks satır=3. öğrenci, 1. indeks sütun=fen
print("İlk 3 öğrencinin tüm notları  :\n", notlar[:3, :])
print("Tüm öğrencilerin İngilizce sütunu (ilk 10):", notlar[:10, 2])

İlk öğrencinin matematik notu : 42.7
Son öğrencinin matematik notu : 36.5
5-10 arası öğrencilerin notları: [51.5 41.9 56.7 54.1 71.9]

3. öğrencinin fen notu        : 95.0
İlk 3 öğrencinin tüm notları  :
 [[42.7 55.4 57. ]
 [57.6 68.8 64.8]
 [84.8 95.  79.2]]
Tüm öğrencilerin İngilizce sütunu (ilk 10): [57.  64.8 79.2 54.7 30.  63.9 39.2 53.4 38.3 81.3]


In [7]:
# Matematikten 80 ve üzeri alan öğrenciler
basarili_mat = matematik[matematik >= 80]
print("Matematikten 80+ alan öğrenci sayısı:", basarili_mat.size)
print("Bu öğrencilerin oranı: %", round(basarili_mat.size / matematik.size * 100, 1))

Matematikten 80+ alan öğrenci sayısı: 6267
Bu öğrencilerin oranı: % 25.1


In [8]:
# Birden fazla koşulu & (ve) ile birleştirebiliriz (her koşul parantez içinde olmalı!)
# Hem matematikten hem fenden 80+ alan öğrenciler
cift_basarili = (matematik >= 80) & (fen >= 80)
print("Hem matematik hem fen 80+ olan öğrenci sayısı:", cift_basarili.sum())  # True'lar 1 sayılır

# | (veya) operatörü: en az bir dersten 90+ alanlar
en_az_bir_90 = (matematik >= 90) | (fen >= 90) | (ingilizce >= 90)
print("En az bir dersten 90+ alan öğrenci sayısı  :", en_az_bir_90.sum())

Hem matematik hem fen 80+ olan öğrenci sayısı: 4163
En az bir dersten 90+ alan öğrenci sayısı  : 5460


In [9]:
# Boolean maskeyi başka bir array'e uygulama:
# Günde 4 saatten fazla çalışan öğrencilerin genel başarı skoru ortalaması
cok_calisanlar = final_yuzde[calisma_saat > 4]
az_calisanlar  = final_yuzde[calisma_saat < 2]

print("4+ saat çalışanların ortalama başarısı: %", round(cok_calisanlar.mean(), 2))
print("2 saatten az çalışanların ortalaması  : %", round(az_calisanlar.mean(), 2))

4+ saat çalışanların ortalama başarısı: % 77.94
2 saatten az çalışanların ortalaması  : % 39.79


In [10]:
# Kategorik sütunla filtreleme: bu veri setinde Pass/Fail yerine harf notu (final_grade) var
# "f" harfi kalan (başarısız) öğrencileri temsil ediyor
kalanlarin_devami = devam[not_harfi == "f"]
gecenlerin_devami = devam[not_harfi != "f"]

print("Kalan öğrenci sayısı:", kalanlarin_devami.size)
print("Kalanların ortalama devam yüzdesi : %", round(kalanlarin_devami.mean(), 1))
print("Geçenlerin ortalama devam yüzdesi : %", round(gecenlerin_devami.mean(), 1))

Kalan öğrenci sayısı: 2955
Kalanların ortalama devam yüzdesi : % 66.0
Geçenlerin ortalama devam yüzdesi : % 76.3


In [11]:
print("=== Matematik Notu İstatistikleri ===")
print("Ortalama       :", round(matematik.mean(), 2))
print("En düşük       :", matematik.min())
print("En yüksek      :", matematik.max())
print("Standart sapma :", round(matematik.std(), 2))
print("Medyan         :", np.median(matematik))

=== Matematik Notu İstatistikleri ===
Ortalama       : 63.79
En düşük       : 0.0
En yüksek      : 100.0
Standart sapma : 20.87
Medyan         : 64.1


In [12]:
# axis parametresi: 2D matriste satır mı sütun mu yönünde işlem yapılacağını belirler
# axis=0 -> sütun bazında (her dersin ortalaması)
# axis=1 -> satır bazında (her öğrencinin ortalaması)

ders_ortalamalari = notlar.mean(axis=0)
print("Ders ortalamaları [Matematik, Fen, İngilizce]:", np.round(ders_ortalamalari, 2))

ogrenci_ortalamalari = notlar.mean(axis=1)
print("İlk 5 öğrencinin kişisel not ortalaması:", np.round(ogrenci_ortalamalari[:5], 2))

Ders ortalamaları [Matematik, Fen, İngilizce]: [63.79 63.75 63.68]
İlk 5 öğrencinin kişisel not ortalaması: [51.7  63.73 86.33 42.2  23.87]


In [13]:
# argmax: en büyük değerin İNDEKSİNİ verir -> en başarılı öğrenciyi bulalım
en_iyi_indeks = final_yuzde.argmax()
print("En yüksek genel başarı skoruna sahip öğrencinin indeksi:", en_iyi_indeks)
print("Öğrenci ID'si  :", satirlar[en_iyi_indeks][0])
print("Başarı skoru   : %", final_yuzde[en_iyi_indeks])
print("Notları [M,F,İ]:", notlar[en_iyi_indeks])
print("Günlük çalışma :", calisma_saat[en_iyi_indeks], "saat")

En yüksek genel başarı skoruna sahip öğrencinin indeksi: 202
Öğrenci ID'si  : 203
Başarı skoru   : % 100.0
Notları [M,F,İ]: [100.   92.8 100. ]
Günlük çalışma : 7.8 saat


In [14]:
# Diyelim ki tüm matematik notlarına 5 puan kaynak eklendi (broadcasting)
mat_kaynakli = matematik + 5
# Ama not 100'ü geçemez -> np.clip ile sınırlıyoruz
mat_kaynakli = np.clip(mat_kaynakli, 0, 100)

print("Önce  (ilk 10):", matematik[:10])
print("Sonra (ilk 10):", mat_kaynakli[:10])
print("Yeni ortalama :", round(mat_kaynakli.mean(), 2), "(eski:", round(matematik.mean(), 2), ")")

Önce  (ilk 10): [42.7 57.6 84.8 44.4  8.9 51.5 41.9 56.7 54.1 71.9]
Sonra (ilk 10): [47.7 62.6 89.8 49.4 13.9 56.5 46.9 61.7 59.1 76.9]
Yeni ortalama : 68.5 (eski: 63.79 )


In [15]:
# Ağırlıklı ortalama hesabı: Matematik %50, Fen %30, İngilizce %20 ağırlıklı olsun
agirliklar = np.array([0.5, 0.3, 0.2])

# (25000,3) matris * (3,) vektör -> broadcasting ile her satır ağırlıklarla çarpılır
agirlikli_ortalama = (notlar * agirliklar).sum(axis=1)

print("İlk 5 öğrencinin ağırlıklı ortalaması:", np.round(agirlikli_ortalama[:5], 2))
print("Genel ağırlıklı ortalama:", round(agirlikli_ortalama.mean(), 2))

İlk 5 öğrencinin ağırlıklı ortalaması: [49.37 62.4  86.74 41.39 20.26]
Genel ağırlıklı ortalama: 63.75


In [16]:
# İlk 12 öğrencinin matematik notunu 3x4'lük bir matrise dönüştürelim
ilk12 = matematik[:12]
print("Orijinal (1D):", ilk12)
print("3x4 matris:\n", ilk12.reshape(3, 4))
print("4x3 matris:\n", ilk12.reshape(4, 3))

Orijinal (1D): [42.7 57.6 84.8 44.4  8.9 51.5 41.9 56.7 54.1 71.9 75.4 62. ]
3x4 matris:
 [[42.7 57.6 84.8 44.4]
 [ 8.9 51.5 41.9 56.7]
 [54.1 71.9 75.4 62. ]]
4x3 matris:
 [[42.7 57.6 84.8]
 [44.4  8.9 51.5]
 [41.9 56.7 54.1]
 [71.9 75.4 62. ]]


In [17]:
# Rastgele örneklem: tüm öğrencilerden rastgele 10 tanesini seçelim
np.random.seed(42)   # tekrarlanabilirlik için tohum sabitliyoruz (derste öğrendik!)

rastgele_indeksler = np.random.choice(matematik.size, size=10, replace=False)  # tekrarsız 10 indeks
print("Seçilen indeksler:", rastgele_indeksler)
print("Bu öğrencilerin matematik notları:", matematik[rastgele_indeksler])
print("Örneklem ortalaması:", matematik[rastgele_indeksler].mean())
print("Tüm veri ortalaması:", round(matematik.mean(), 2))

Seçilen indeksler: [ 6868 24016  9668 13640 14018  7488  5804 12909  3386  9567]
Bu öğrencilerin matematik notları: [71.  41.1 73.2 56.1 49.9 79.4 19.9 77.6 54.2 81.1]
Örneklem ortalaması: 60.35000000000001
Tüm veri ortalaması: 63.79
